library(wbstats)
library(data.table)
library(googleVis)
library(ggplot2)
library(gplots)
library(reshape2)
library(plyr)
library(dplyr)


indicators = wbindicators()
countries <- data.table(wbcountries())


# Define UI for application that plots the data frame.
ui <- shinyUI(fluidPage(
  titlePanel("Analyze data from around the globe"),
  tabsetPanel(
    tabPanel("Welcome Data Analysis Platform",
             titlePanel("Welcome to Data Portal."),
             mainPanel(
               tags$p("This application is intended for purely academic use. It interacts with the database managed by the World Bank, and lets 
                      users to select the data for a particular region or countries. Users can also visualize variables of interest and examine the trend 
                      in the data. The application will compute the percentage change in the variable of interest for countries. The plots and statistics 
                      generated by this application can be used with proper acknowledgements to the tool."),
               tags$a(href="http://databank.worldbank.org/data/home.aspx", "Link Here"),
               tags$br(),
               tags$p("The users can choose variable(s) of interest and examine how that variable compares between countries. Multiple variables and countries 
                      can be selected for comparison. The indicators has indicatorID assigned to it as maintained in the WorldBank Data."), 
               tags$br(), 
               tags$p("Recent statistics of the chosen variable is plotted."),
               img(src = "image.png", height = 300, width = 900), 
               tags$p("Developed in the R Shiny framework and maintained by Bishal Paudel. Please direct any questions/concerns to paudelbb@gmail.com")
               )
    ),
    tabPanel("Select Data",
             titlePanel("Select variables for comparison"),
             sidebarLayout(
               sidebarPanel(
                 selectInput('indicator', label = "Choose indicator(s)", choices = c(unique(indicators$indicator)), multiple = T),
                 selectInput('country', label = "Choose country(ies)", choices = c(unique(countries$country)), multiple = T)),
               mainPanel(
                 dataTableOutput('contents1')
               )
             )),
    tabPanel("Data Visualization",
             pageWithSidebar(
               headerPanel('Choose variables for plot'),
               sidebarPanel(
                 # "Empty inputs" - they will be updated after the data is uploaded
                 selectInput('identifier', 'identifer', ""),
                 selectInput('xcol', 'X Variable', ""),
                 selectInput('ycol', 'Y Variable', "", selected = "")),
               mainPanel(
                 plotOutput('MyPlot')))), 
    tabPanel("Data Summary", 
             splitLayout(
               plotOutput('summaryPlot'),
               dataTableOutput(outputId = "summary"))), 
    tabPanel("Recent Statistics", 
             pageWithSidebar(
               headerPanel('Choose variables for plot'),
               sidebarPanel(
                 # "Empty inputs" - they will be updated after the data is uploaded
                 numericInput(inputId = 'time', label = 'Starting time', value = 1980, min = 1960, max = 2017), 
                 selectInput('varAn', 'What variable to analyze?', "")),
               mainPanel(
                 plotOutput('stats'),
                 dataTableOutput(outputId = 'data1'),
                 dataTableOutput(outputId = 'data'))))
             )
    )
)

server <- shinyServer(function(input, output, session) {
  options(shiny.maxRequestSize=30*1024^2)
  # added "session" because updateSelectInput requires it
  data1 <- reactive({ 
    req(input$indicator) ## ?req #  require that the input is available
    req(input$country) ## ?req #  require that the input is available
    indId = match(input$indicator, indicators$indicator)
    #indicatorid = indicators[indId,]$indicatorID
    myDT = data.table(wb(indicator = c(indicators[indId,]$indicatorID), mrv = 60, return_wide = TRUE))
    updateSelectInput(session, inputId = 'identifier',  label = 'identifer',   choices = names(myDT), selected = names(myDT))
    updateSelectInput(session, inputId = 'xcol',  label = 'X Variable',        choices = names(myDT), selected = names(myDT))
    updateSelectInput(session, inputId = 'ycol',  label = 'Y Variable',        choices = names(myDT), selected = names(myDT)[2])
    dN = myDT[(myDT$country %in% input$country),]
    dN = data.frame(dN)
  })
  data2 <- reactive({
    dn = data.frame()
    for(w in unique(data1()$country)){
      tn = subset(data1(), country == w)
      data = subset(tn, tn$date == max(tn$date))
      dn = rbind(dn, data)
    }
    dn
  })
  data3 <- reactive({
    updateSelectInput(session, inputId = 'varAn',  label = 'Variable to analyze', choices = names(data1()), selected = names(data1()))
    dates = c(input$time, max(data1()$dat))
    temp <- subset(data1(), date >= input$time)
    temp1 = temp[(temp$date %in% dates),]
    temp1
  })
  data4 <- reactive({
    dn = data.frame()
    for(c in unique(data3()$country)){
      st1 = subset(data3(), country ==c)
      st = st1[,c(input$identifier, input$xcol, input$varAn)]
      st = transpose(data.table(data.frame(st)))
      st = st[-1,]
      st = c(as.numeric(unlist(st)))
      diff1 = st[3] - st[1]; diff2 = st[4] - st[2]
      df = data.frame(country = unique(st1$country), rate = (diff2/st[2])/diff1 * 100)
      dn = rbind(dn, df)
    }
    dn
  })
  
  output$contents1 <- renderDataTable({data1()})
  output$MyPlot <- renderPlot({
      x <- data1()[ , c(input$identifier,input$xcol, input$ycol)]
      colnames(x) <- c("country", "b", "c")
      sp = ggplot(x, aes(x=b, y=c, col=country)) + geom_point() + labs(x=paste0(input$xcol), y=paste0(input$indicator), title=paste0(input$indicator))
      sp + theme_bw() + theme(axis.text.x = element_text(angle=45)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
  })
 
  output$summaryPlot <- renderPlot({
    x <- data2()[ , c(input$identifier,input$xcol, input$ycol)]
    colnames(x) <- c("country", "b", "c")
    ggplot(data=x, aes(x=country, y=c, fill=country)) + geom_bar(stat="identity") + labs(y=paste0(input$ycol), title=paste0(input$indicator))
  })
  output$stats <- renderPlot({
    y <- data4()[,]
    ggplot(data=y, aes(x=country, y=rate, fill=country)) + geom_bar(stat="identity") + labs(y=paste0("% change in ", input$ycol), title=paste0("% change in ",input$indicator))
  })
  output$summary <- renderDataTable({data2()})
  output$data <- renderDataTable({data3()})
  output$data1 <- renderDataTable({data4()})
})

shinyApp(ui, server)



